# Generated by Django 5.2.3 on 2025-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
