# Generated by Django 5.2.3 on 2025-07-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
